### PR TITLE
feat: support jinnai system

### LINKED ISSUE #146: Add Support 陣内システム
VRChatに送るURLを[陣内システム](https://nextnex.com/)経由にするエンドポイントを使用するオプションを追加する

ex) /nextnex

### PR DESCRIPTION
**Pull request by koyashiro**
- closes #146

image
image

### CODE REVIEW

**Review by bootjp — APPROVED** [review]
LGTM

**Comment by Give535** [comment]
https://github.com/vrc-plugin/send_vrc_extension/pull/152

**Comment by Give535** [comment]
https://github.com/vrc-plugin/send_vrc_extension/pull/152

**Comment by Give535** [comment]
https://github.com/vrc-plugin/send_vrc_extension/pull/152

**Comment by Give535** [comment]
152

**Pull request merged**
